---

- name: stop syslog-ng service on first installation
  service:
    name: syslog-ng
    state: stopped
  become: yes
  when: lts_syslogng_installed.changed

- name: remove default syslog-ng rules
  blockinfile:
    path: "/etc/syslog-ng/syslog-ng.conf"
    marker: "{mark}"
    marker_begin: "# Log paths"
    marker_end: "###"
    state: absent
  notify: restart syslog-ng
  become: yes
