---

- name: add apt key
  apt_key:
    url: "{{ lts_apt_key }}"
    state: present
  become: yes

- name: add apt repo
  apt_repository:
    repo: "{{ lts_apt_repo }}"
    state: present
  become: yes

- name: install syslog-ng
  apt:
    name: syslog-ng
    state: present
  become: yes
  register: lts_syslogng_installed
